version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/trvapp/zip
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 744

hooks:
  AfterInstall:
    - location: stop.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: root

  ValidateService:
    - location: health.sh
      timeout: 60
      runas: root