version: "3"
services:

  spring1:
    build: .
    image: spring
    container_name: real1
    ports:
      - 8081:8081
    volumes:
      - ./:/root/
    environment:
      active: real1
  spring2:
    build: .
    image: spring
    container_name: real2
    ports:
      - 8082:8082
    volumes:
      - ./:/root/
    environment:
      active: real2